[mypy]
python_version = 3.14
files = custom_components/jablotron100
explicit_package_bases = True
check_untyped_defs = True
no_implicit_optional = True
show_error_codes = True
warn_redundant_casts = True
warn_unused_ignores = True
